# Generated by Django 5.0.4 on 2024-06-12 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_options_alter_user_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='class_num',
            field=models.CharField(default='', max_length=5),
        ),
    ]
