# Generated by Django 5.0.6 on 2024-06-17 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClassRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('location', models.CharField(blank=True, max_length=30)),
                ('loc_num', models.CharField(blank=True, max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loc_num', models.CharField(max_length=10)),
                ('image', models.ImageField(upload_to='images/map')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('subject', models.CharField(max_length=30)),
                ('location', models.CharField(max_length=30)),
                ('profile_img', models.ImageField(blank=True, upload_to='images/profile')),
                ('introduce', models.CharField(blank=True, max_length=50)),
            ],
        ),
    ]
