# Generated by Django 5.0.4 on 2024-04-09 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='cnotents',
            new_name='contents',
        ),
    ]
