# Generated by Django 5.0.4 on 2024-05-31 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_classroom_teachers_delete_post'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Teachers',
            new_name='Teacher',
        ),
        migrations.AlterField(
            model_name='classroom',
            name='location',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
