# Generated by Django 5.0.4 on 2024-06-06 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_classroom_img_remove_classroom_map_img_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loc_num', models.CharField(max_length=10)),
                ('image', models.ImageField(upload_to='images/map')),
            ],
        ),
    ]
